/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Auxfacturacion
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuAdministrativo = new javax.swing.JMenu();
        jCrearUsuario = new javax.swing.JMenuItem();
        jConsultarUsuario = new javax.swing.JMenuItem();
        MenuItem = new javax.swing.JMenu();
        jCrearItem = new javax.swing.JMenuItem();
        jActualizarItem = new javax.swing.JMenuItem();
        jConsultarItem = new javax.swing.JMenuItem();
        MenuContratacion = new javax.swing.JMenu();
        jCrearEmpresa = new javax.swing.JMenuItem();
        jConsultarEmpresa = new javax.swing.JMenuItem();
        jAgregarTarifas = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 204, 255));

        MenuArchivo.setText("Archivo");

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuArchivo.add(jMenuItem2);

        jMenuBar1.add(MenuArchivo);

        MenuAdministrativo.setText("Administrativo");

        jCrearUsuario.setText("Crear usuario");
        jCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearUsuarioActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(jCrearUsuario);

        jConsultarUsuario.setText("Consultar usuario");
        jConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarUsuarioActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(jConsultarUsuario);

        jMenuBar1.add(MenuAdministrativo);

        MenuItem.setText("Item");

        jCrearItem.setText("Crear item");
        jCrearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearItemActionPerformed(evt);
            }
        });
        MenuItem.add(jCrearItem);

        jActualizarItem.setText("Actualizar item");
        jActualizarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarItemActionPerformed(evt);
            }
        });
        MenuItem.add(jActualizarItem);

        jConsultarItem.setText("Consultar items");
        jConsultarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarItemActionPerformed(evt);
            }
        });
        MenuItem.add(jConsultarItem);

        jMenuBar1.add(MenuItem);

        MenuContratacion.setText("Contratación");

        jCrearEmpresa.setText("Crear Empresa");
        jCrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearEmpresaActionPerformed(evt);
            }
        });
        MenuContratacion.add(jCrearEmpresa);

        jConsultarEmpresa.setText("Consultar Empresa");
        jConsultarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarEmpresaActionPerformed(evt);
            }
        });
        MenuContratacion.add(jConsultarEmpresa);

        jAgregarTarifas.setText("Agregar Tarifas");
        jAgregarTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarTarifasActionPerformed(evt);
            }
        });
        MenuContratacion.add(jAgregarTarifas);

        jMenuBar1.add(MenuContratacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearUsuarioActionPerformed
        GuiUsuario crear = new GuiUsuario();
        crear.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCrearUsuarioActionPerformed

    private void jConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarUsuarioActionPerformed
        GuiConsultaUsuario crear = new GuiConsultaUsuario();
        crear.setVisible(true);
        dispose();
    }//GEN-LAST:event_jConsultarUsuarioActionPerformed

    private void jConsultarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarItemActionPerformed
        GuiConsultarItems crear = new GuiConsultarItems();
        crear.setVisible(true);
        dispose();
    }//GEN-LAST:event_jConsultarItemActionPerformed

    private void jCrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearEmpresaActionPerformed
        GuiEmpresa crear = new GuiEmpresa();
        crear.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCrearEmpresaActionPerformed

    private void jConsultarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarEmpresaActionPerformed
        GuiConsultaEmpresa crear = new GuiConsultaEmpresa();
        crear.setVisible(true);
        dispose();
    }//GEN-LAST:event_jConsultarEmpresaActionPerformed

    private void jAgregarTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarTarifasActionPerformed
        GuiTarifas crear = new GuiTarifas();
        crear.setVisible(true);
        dispose();
    }//GEN-LAST:event_jAgregarTarifasActionPerformed

    private void jCrearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearItemActionPerformed
        GuiCrearItem principal = new GuiCrearItem();
            principal.setVisible(true);
            dispose();
    }//GEN-LAST:event_jCrearItemActionPerformed

    private void jActualizarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarItemActionPerformed
        GuiActualizarItem principal = new GuiActualizarItem();
            principal.setVisible(true);
            dispose();
    }//GEN-LAST:event_jActualizarItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdministrativo;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuContratacion;
    private javax.swing.JMenu MenuItem;
    private javax.swing.JMenuItem jActualizarItem;
    private javax.swing.JMenuItem jAgregarTarifas;
    private javax.swing.JMenuItem jConsultarEmpresa;
    private javax.swing.JMenuItem jConsultarItem;
    private javax.swing.JMenuItem jConsultarUsuario;
    private javax.swing.JMenuItem jCrearEmpresa;
    private javax.swing.JMenuItem jCrearItem;
    private javax.swing.JMenuItem jCrearUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
